### ISSUE TITLE
storm-core.jar 0.9.1-incubating-SNAPSHOT is missing in apache maven repo?

### ISSUE THREAD

**Issue by pershyn** [ptgoetz/storm-hdfs#4]
Got the latest version (e7adf3f), unable to compile it with maven:
`The POM for org.apache.storm:storm-core:jar:0.9.1-incubating-SNAPSHOT is missing, no dependency information available
...
[ERROR] Failed to execute goal on project storm-hdfs: Could not resolve dependencies for project org.apache.storm:storm-hdfs:jar:0.0.2-SNAPSHOT: Could not find artifact org.apache.storm:storm-core:jar:0.9.1-incubating-SNAPSHOT
`

Same happens to 0.9.0.1:
`[ERROR] Failed to execute goal on project storm-hdfs: Could not resolve dependencies for project org.apache.storm:storm-hdfs:jar:0.0.2-SNAPSHOT: Could not find artifact org.apache.storm:storm-core:jar:0.9.0.1 in central (http://repo.maven.apache.org/maven2)`

Am I doing something wrong or the storm-core.jar is not yet in the repo?

---

Yet I have checked http://mvnrepository.com/search.html?query=storm-core and http://search.maven.org/
Found 0.9.0.1 at https://clojars.org/storm/storm-core, but the group id is old though: `<groupId>storm</groupId>`

**Comment by ptgoetz** [comment]
I pushed a commit that should fix that for you. I was testing against the next version of storm, which has yet to be released.

**Comment by ashok-gupta** [comment]
I am afraid it is still not working for me. I tried including the following in pom.xml of my project but the download of the artifact fails. Other dependencies from maven central are getting download properly to ~/.m2/repository.

```
<dependency>
   <groupId>org.apache.storm</groupId>
    <artifactId>storm</artifactId>
    <version>0.9.1-incubating</version>
</dependency>

```

**Comment by ashok-gupta** [comment]
I am able to get storm-core though as follows.

```
<dependency>
   <groupId>org.apache.storm</groupId>
    <artifactId>storm-core</artifactId>
    <version>0.9.1-incubating</version>
</dependency>
```

**Comment by praveenkishor123** [comment]
I am also getting the below error while trying to build the project

[ERROR] Failed to execute goal on project chapter1: Could not resolve dependencies for project storm.blueprints:chapter1:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.apache.storm:storm-core:jar:0.9.3: Failed to read artifact descriptor for org.apache.storm:storm-core:jar:0.9.3: Could not transfer artifact org.apache.storm:storm-core:pom:0.9.3 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.16.215] failed: Connection timed out: connect -> [Help 1]

**Comment by SaiPriyanka0249** [comment]
Hi,
when i open my Netbeans IDE,right click my project and  i click on  build and clean project, i am getting error like this
Failed to execute goal on project sunway-pcv-production: Could not resolve dependencies for project od.sunway.pcv:sunway-pcv-production:bundle:5.0-SNAPSHOT: Could not find artifact org.joget:wflow-core:jar:5.0-SNAPSHOT -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException.

if any one knows could you please help me
